### PR TITLE
Added three custom Instruments commonly used

### PR DESCRIPTION
**Pull request by TheGreatFoxxy**
added three commonly used custom instruments
1. Firework Blast
2. Nether Portal Trigger
3. Experience Orb Pickup

### CODE REVIEW

**Comment by GarboMuffin** [comment]
Just adding these files doesn't work. Lots of internal changes need to be made for custom instruments to be supported.

This project is largely abandoned. It's not being actively worked on and probably won't be for quite a while.

**Comment by pressstartgaming** [comment]
Does this help? If you need a co-author, I'm your guy.

**Comment by ghost** [comment]
nbsplayer is not maintained. this will not be merged.

feel free to maintain your own fork of the project, if that's something you want to do. the project is now under the MIT license so you have full permission to do that.

**Comment by ghost** [comment]
tip: to actually deploy the website to GitHub pages, you have to run the build script & update some files.

easiest way is to clone another copy of the repo, and switch to the gh-pages branch (`git checkout gh-pages`) in that one.

then do `npm run build` in this repository (on branch master) and manually copy the `dist` folder to the gh-pages local copy, and push gh-pages to github. github.io only cares about the gh-pages branch.

you can probably automate this with things like Travis CI, nbsplayer used to do that (`.travis.yml`)

**Comment by TheGreatFoxxy** [comment]
Can you do like a screencaster like that or some form of walkthrough? I'm kinda new to this sorta thing.

**Pull request closed without merging**
